@startuml
老师"1" - "n"课程 : 上课 >
老师"1" --|> "1"用户 : 源于 >
老师 : 教师职工工号
老师 : 用户id

学生"1" --|> "1"用户 : 源于 >
学生"1" - "n"成绩 : 查看 >
学生"n" -* "1"班级 : 组成 >
学生"1" -- "n"选课 : 选课 >
学生 : 学号
学生 : 用户id

成绩"n" -* "1"实验 : 得到 <
成绩 : 分数
成绩 : 实验id
成绩 : 实验所在github地址
成绩 : 学生学号
成绩 : 概念分数
成绩 : 语言分数
成绩 : 结构分数
成绩 : 逻辑分数
成绩 : 评阅时间

实验"n" --* "1"课程 : 拥有 <
实验"1" -- "n"选课
实验 : 实验id
实验 : 课程id
实验 : 教师职工工号
实验 : 班级
实验 : 实验id
实验 : 选课情况
实验 : 开设时间

用户 : 用户id
用户 : 真实姓名
用户 : github用户名
用户 : 用户密码
用户 : 修改时间

班级"1..4" -- "1"课程
班级 : 班级id
班级 : 班级所在年级
班级 : 班级所在专业

选课 : 所选课程id
选课 : 选课学生id
选课 : 选课教师id
选课 : 教师选课时间
选课 : 学生选课时间

课程"1" -- "n"选课 : 选择 <
课程 : 课程id
课程 : 教师职工工号
课程 : 班级id
课程 : 老师是否选课
课程 : 学生是否选课
课程 : 开课时间
@enduml