@startuml

title:“登录”用例顺序图

actor 用户
participant 用户类型
participant 用户名
participant 密码
participant cookie

activate 用户
    用户->用户类型:选择用户类型
    activate 用户类型
        用户类型->用户名:输入用户名
        activate 用户名
            用户名->密码:输入密码
            activate 密码
                opt 用户名或密码不正确
                    密码->用户:登录失败
                end opt
                密码->cookie:添加cookie
                activate cookie
                    cookie->用户:登录成功
                deactivate cookie
            deactivate 密码
        deactivate 用户名
    deactivate 用户类型



deactivate 用户

@enduml
