@startuml

left to right direction

actor :用户:
actor :学生:
actor :教师:
学生 --|> 用户
教师 --|> 用户

package 用户用例集 {
    用户 --> (登录)
    用户 --> (登出)
    用户 --> (查看用户信息)
    用户 --> (修改用户信息)
    用户 --> (修改密码)
}

package 学生用例集 {
    学生 --> (选课)
    学生 --> (修改实验地址)
    学生 --> (查看成绩)
}

package 教师用例集 {
    教师 --> (维护科目)
    (维护科目) .> (维护课程) : <<extends>>
    教师 --> (维护课程)
    (维护课程) .> (选择上课班级) : <<extends>>
    教师 --> (选择上课班级)
    教师 --> (维护实验)
    教师 --> (查看学生列表)
    教师 --> (维护学生账号)

    package 成绩用例集 {
        教师 --> (评阅概念分数)
        教师 --> (评阅语言分数)
        教师 --> (评阅结构分数)
        教师 --> (评阅逻辑分数)
        教师 --> (检查是否抄袭)
        (评阅概念分数) .> (评阅实验) : <<include>>
        (评阅语言分数) .> (评阅实验) : <<include>>
        (评阅结构分数) .> (评阅实验) : <<include>>
        (评阅逻辑分数) .> (评阅实验) : <<include>>
        教师 --> (评阅实验)
    }
}



@enduml